--
-- TODO:
--

local function loadFishTank()
	
	-- Call the loader to load the fish tank
	msg.post("Loader:/Loader", "load FishTank")
	
end

-- Executes when the script first loads
function init(self)
	-- Acquires input focus
	msg.post(".", "acquire_input_focus")
end

-- Executes when the script recieves input
function on_input(self, action_id, action)

	-- Gets the 4 Option nodes
	local optionSelect = {gui.get_node("FreshwaterChoice"),gui.get_node("SaltwaterChoice"),gui.get_node("DecorChoice"),gui.get_node("FishTankSign")}
	
	-- If there is no specific action
	if action_id == nil then

		-- Gets the 4 glows
		local optionsGlow = {gui.get_node("FreshGlow"),gui.get_node("SaltGlow"),gui.get_node("DecorGlow"),gui.get_node("TankSignGlow")}

		-- Sentinel variable to determine if the user is currently hovering ofer a node
		local hovering = false

		-- Iterates through the option nodes
		for i=1,#optionSelect,1 do

			-- Check if one of the nodes is being hovered over
			if gui.pick_node(optionSelect[i], action.x, action.y) then
				-- Sets hovering to true
				hovering = true

				-- Sets the glow of the hovered item to visible
				gui.set_visible(optionsGlow[i],true)

				-- Iterates through the item glow nodes
				for j=1,#optionsGlow do

					-- If the number does not equal the currently chosen node
					if j ~= i then
						-- Set the glow not visible
						gui.set_visible(optionsGlow[j],false)
					end

				end

				-- Breaks the loop to avoid unnecessary code execution
				break
				
			end
			
		end

		-- If the user is not hovering over any of the nodes
		if not hovering then

			-- Iterate through the glows
			for k=1,#optionsGlow do
				-- Set all of them to not visible
				gui.set_visible(optionsGlow[k],false)
			end

		end
		
	end

	-- If the user left clicks
	if action_id == hash("LeftClick") and action.pressed then

		-- Gets the return arrow node
		local back = gui.get_node("ReturnArrow")

		-- If the user selects the return arrow
		if gui.pick_node(back, action.x, action.y) then

			-- Calls the loader to load the main crane screen
			msg.post("Loader:/Loader", "load Crane")

		-- If the user clicked on anything else
		else

			-- Iterate through the option nodes
			for i=1,#optionSelect,1 do

				-- If the node was clicked
				if gui.pick_node(optionSelect[i], action.x, action.y) then

					-- If i is less than 4, meaning it's one of the set options
					if i < 4 then
						-- Sends a message to the loader to load the item collection scene, passing the set number
						msg.post("Loader:/Loader", "load itemCollection", {set = i})
					-- If i is greater then 3, only the fish tank
					else 
						local to_color = gui.get_color(gui.get_node("black"))
						to_color.w = 1
						gui.animate(gui.get_node("black"), gui.PROP_COLOR, to_color, gui.EASING_IN, .5, 0, loadFishTank)
					end

				end

			end

		end

	end

end

function on_message(self, message_id, message, sender)
	
	if message_id == hash("Opening") then

		gui.set_color(gui.get_node("black"), vmath.vector4(0,0,0,0))
		
	end
	
end

-- Unused Functions

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
