
-- Local Variables
-- Array that keeps track of the board positions
local board = {0,0,0,0,0,0,0,0,0}

-- Boolean to keep track of whether it's the players turn
local playerTurn = true

-- Boolean to keep track of whether the game has ended
local gameEnd = false

-- Custom Function
-- Called to evaluate the board and check whether a line of 3 has happenened or if there's no available spaces to play
-- Determines whether the player or the bot won, updates appropriate variables
-- Sends a message to self to call correct animations
local function evaluate(player)

	-- Set up a variable to track if there is a winner
	local winner = 0

	-- Checks each possible configuration of a line of 3
	-- Checks if they're not set to 0 and all equal (so all 1 or all 2)
	-- Only checks if the first item in the list is set to 0 since if it isn't the rest will always be fine
	-- Sets local variable winner to true to indicate that someone has won

	--123
	if board[1] ~= 0 and board[1] == board[2] and board[1] == board[3] then
		winner = board[1]
	--147
	elseif board[1] ~= 0 and board[1] == board[4] and board[1] == board[7] then
		winner = board[1]
	--159
	elseif board[1] ~= 0 and board[1] == board[5] and board[1] == board[9] then
		winner = board[1]
	--258
	elseif board[2] ~= 0 and board[2] == board[5] and board[2] == board[8] then
		winner = board[2]
	--369
	elseif board[3] ~= 0 and board[3] == board[6] and board[3] == board[9] then
		winner = board[3]
	--357
	elseif board[3] ~= 0 and board[3] == board[5] and board[3] == board[7] then
		winner = board[3]
	--456
	elseif board[4] ~= 0 and board[4] == board[5] and board[4] == board[6] then
		winner = board[4]
	--789
	elseif board[7] ~= 0 and board[7] == board[8] and board[7] == board[9] then
		winner = board[7]
	end

	-- If the're a winner
	if winner ~= 0 then

		-- Set gameEnd to true so the user can't click on the board
		gameEnd = true

		-- Check if the last move was the player
		if winner == 1 then
			-- Increases the global token value
			data["tokens"] = data["tokens"]+1
			-- Update the token text
			gui.set_text(gui.get_node("TokenText"), data["tokens"])
			-- Increases the global tacker of fishtactoe wins
			data["FishTacToeWins"] = data["FishTacToeWins"]+1
			-- Update the win text with the global number of wins
			gui.set_text(gui.get_node("winsInformation"),"Wins: "..data["FishTacToeWins"])
			-- Sets the end game text to "You Win!"
			gui.set_text(gui.get_node("endGameText"),"You Win!")

		-- Check if the last move was the bot
		elseif winner == 2 then
			-- Update the global fishtactoe lost tracker
			data["FishTacToeLosses"] = data["FishTacToeLosses"]+1
			-- Update the losses number with the global fishtactoe losses
			gui.set_text(gui.get_node("lossInformation"),"Losses: "..data["FishTacToeLosses"])
			-- Sets the end game text to "You Lose!"
			gui.set_text(gui.get_node("endGameText"),"You Lose!")

		end

		-- Sets the end game text to visible
		gui.set_visible(gui.get_node("endGameText"),true)
		-- enable and set visible the play again node and it's text
		gui.set_enabled(gui.get_node("playAgain"), true)
		gui.set_visible(gui.get_node("playAgain"), true)
		gui.set_visible(gui.get_node("playAgainText"),true)

		-- Saves the changed values to the save file
		sys.save(path,data)

		-- Returns to avoid executing unnecessary code
		return

	end

	-- Sets up a boolean to check if the board is full
	local noSpacesLeft = false
	-- Iterates through the board
	for i = 1, 9, 1 do
		-- Checks if any of the spaces are empty
		if board[i] == 0 then
			-- Sets to true to indicate there are spaces left
			noSpacesLeft = true
		end
	end

	-- Checks if there is no winner, and also there are no open spaces left
	if not noSpacesLeft then

		-- Sets gameEnd to true 
		gameEnd = true

		-- updates the global fishtactoe stalemate counter
		data["FishTacToeStalemates"] = data["FishTacToeStalemates"]+1
		-- Update the losses number with the global fishtactoe losses
		gui.set_text(gui.get_node("stalemateInformation"),"Stalemates: "..data["FishTacToeStalemates"])
		-- Sets the end game text to visible
		gui.set_visible(gui.get_node("endGameText"),true)
		-- Sets the end game text to "Stalement"
		gui.set_text(gui.get_node("endGameText"),"Stalemate")
		-- enable and set visible the play again node and it's text
		gui.set_enabled(gui.get_node("playAgain"), true)
		gui.set_visible(gui.get_node("playAgain"), true)
		gui.set_visible(gui.get_node("playAgainText"),true)

		-- Saves the changed values to the save file
		sys.save(path,data)

		-- Returns to avoid executing unnecessary code
		return

	-- If there's no winner and still spaces left
	else 

		-- Sends message to self to update variables depending on which player called evaluate
		msg.post(".","Change Turns", {caller = player})
		
	end

end

-- Custom Function
-- Selects a random open spot on the board for the bot
-- Displays the correct sprite in the chosen spot
-- Calls evaluate to determine if anyone won
local function fishTurn()			

	-- Sets the fish thinking nods to not visible
	gui.set_visible(gui.get_node("FishThinking"), false)

	-- Selects a random number between 1 and 9
	local spotSelect = math.random(1,9)
	-- Checks if the spot selected is already full
	while board[spotSelect] == 1 or board[spotSelect] == 2 do
		-- Selects a new spot until it finds an empty one
		spotSelect = math.random(1,9)
	end

	-- Sets the chosen board spot to 2, the bots number
	board[spotSelect] = 2
	-- Calls the loader to play the placing sound
	msg.post("Loader:/Loader", "Sound", {sound = 5})
	-- Sets the chosen node to visible
	gui.set_visible(gui.get_node("box"..spotSelect), true)
	-- Sets the chosen node to the bots icon
	gui.play_flipbook(gui.get_node("box"..spotSelect), "sea-urchin")
	-- Sends a message to self to evaluate if someone has won, passing it's number
	evaluate(2)

end

-- Custom Function
-- Checks if the spot the user clicked is already visible
-- Plays the correct sound and displays the correct sprite
-- Calls evaluate to see if anyone won
local function playerPlace(space)

	-- Checks if the board space has already been marked 
	if board[space] ~= 1 and board[space] ~= 2 then
		-- Set playerTurn to false so they can't click on other nodes
		playerTurn = false
		-- Set the space to 1, indicating that the player chose this space
		board[space] = 1
		-- Call the loader to play the placing sound
		msg.post("Loader:/Loader", "Sound", {sound = 5})
		-- Sets the node in that board space to visible
		gui.set_visible(gui.get_node("box"..space), true)
		-- Set the node to the player animation
		gui.play_flipbook(gui.get_node("box"..space), "starfish")
		-- Sends a message to self to evaluate whether the player has one. Passes 1 to tell the script that last played was the player
		evaluate(1)
	end

end

-- Custom Function
-- Handles resetting the game for a new play
local function Reset() 
	
	-- Sets the board array back to default
	board = {0,0,0,0,0,0,0,0,0}
	-- Sets player turn to true as they always go first
	playerTurn = true
	-- Set gameEnd back to false so players can interact with the board
	gameEnd = false
	-- Sets all the end game nodes and the board nodes to not visible
	gui.set_visible(gui.get_node("endGameText"), false)
	gui.set_enabled(gui.get_node("playAgain"), false)
	gui.set_visible(gui.get_node("playAgain"), false)
	gui.set_visible(gui.get_node("playAgainText"),false)
	gui.set_visible(gui.get_node("box1"), false)
	gui.set_visible(gui.get_node("box2"), false)
	gui.set_visible(gui.get_node("box3"), false)
	gui.set_visible(gui.get_node("box4"), false)
	gui.set_visible(gui.get_node("box5"), false)
	gui.set_visible(gui.get_node("box6"), false)
	gui.set_visible(gui.get_node("box7"), false)
	gui.set_visible(gui.get_node("box8"), false)
	gui.set_visible(gui.get_node("box9"), false)
	
end

-- Executes the first time the script is loaded
function init(self)
	-- Acquires input focus
	msg.post(".","acquire_input_focus")
	-- Sets the token text to the global variable
	gui.set_text(gui.get_node("TokenText"),data["tokens"])
	-- Sets the random seed based on the clock
	math.randomseed(socket.gettime() * 100000)
end

-- Executes when the script receives input
function on_input(self, action_id, action)

	-- If the player left clicks
	if action_id == hash("LeftClick") and action.pressed then

		-- Gets the X node
		local goBack = gui.get_node("Exit")

		-- If the player clicks the X node
		if gui.pick_node(goBack, action.x, action.y) then
			-- Call the loader to load the minigame select screen
			msg.post("Loader:/Loader", "load MiniGameSelect")
		end

		-- Check if the game has not ended, by checking that all of the end conditions nodes are false
		if not gameEnd then

			-- If it's the players turn
			if playerTurn then

				-- Get the nodes for each position on the board
				local boardSpaces = {gui.get_node("box1"),gui.get_node("box2"),gui.get_node("box3"),gui.get_node("box4"),gui.get_node("box5"),gui.get_node("box6"),gui.get_node("box7"),gui.get_node("box8"),gui.get_node("box9")}

				-- Iterates through the board space nodes
				for i=1,#boardSpaces do

					-- if that node was the clicked one
					if gui.pick_node(boardSpaces[i], action.x, action.y) then
						-- Call playerPlace to place or reject the users symbol
						playerPlace(i)
						-- Calls return to stop iterating as the user can only click on one node at a time
						return
					end

				end
				
			end

		-- If the game has ended, so one of the win conditions boolean is true
		elseif gameEnd then
		
			-- Get the now visible play again button node 
			local playAgain = gui.get_node("playAgain")
			-- If the player clicked the play again node
			if gui.pick_node(playAgain, action.x, action.y) then
				-- Call the reset function
				Reset()
			end
			
		end
		
	end
	
end

-- Executes whenever the script receives a message
function on_message(self, message_id, message, sender)

	-- If the message id is Update (sent from the loader whenever the page is enabled)
	if message_id == hash("Update") then
		
		-- Updates the tokens text & the gameEnd information board
		gui.set_text(gui.get_node("TokenText"),data["tokens"])
		gui.set_text(gui.get_node("stalemateInformation"),"Stalemates: "..data["FishTacToeStalemates"])
		gui.set_text(gui.get_node("winsInformation"),"Wins: "..data["FishTacToeWins"])
		gui.set_text(gui.get_node("lossInformation"),"Losses: "..data["FishTacToeLosses"])
		-- Calls reset 
		Reset()

	-- If it receives message Change Turns from itself
	elseif message_id == hash("Change Turns") then
		-- If the message was sent by the players input
		if message.caller == 1 then
			-- Set the fishthinking node to visible
			gui.set_visible(gui.get_node("FishThinking"), true)
			-- Play the fish thinking animation, and call fishThinkEnd when it's done
			gui.play_flipbook(gui.get_node("FishThinking"), "FishThinking", fishTurn)
		-- If the messager was sent by the bot
		elseif message.caller == 2 then
			-- Sets playerTurn to true so they can take their turn
			playerTurn = true
		end
	end	
	
end
