-- 
-- TODO: 
-- 

-- Local Variables

-- Local Array holding the values of the cards in the match game
local cards = {1,1,2,2,3,3}

-- Local array holding the spots of where the cards are assigned
local cardsPlace = {0,0,0,0,0,0}

-- Variables keeping track of whether they lost or won
local gameEnd = false

-- Local small array to kee track of the positions of the cards flipped over
local currentPairFlipped = {0,0}

-- Variable to keep track of how many cards have been flipped
local flippedAmount = 0

-- Variable keeping track of the total number of flips the player has left
local flipsLeft = 10

-- Array keeping track of which cards have been flipped over
local flippedOver = {0,0,0,0,0,0}

-- Boolean keeping track of whether the game is currently evaluating a match
local evaluating = false

-- Custom Function
-- Evaluates whether all cards have been flipped over, meaning all matches have been found
local function winEvaluate()

	-- Set a sentinel variable to true
	local winner = true
	
	-- Iterate through the cardsPlace array
	for i = 1,#cardsPlace, 1 do
		-- Check if any of the positions are equal to 0
		if flippedOver[i] == 0 then
			-- Set winner to false as not all the cards have been revealed
			winner = false
		end								
	end	

	-- If winner is still true, meaning all cards have been flipped over
	if winner then
		-- Set gameEnd to true
		gameEnd = true	
		-- Increase global tokens
		tokens = tokens+1
		-- Increase global match played
		MatchPlayed = MatchPlayed +1
		-- Update On Screen Tokens Text
		gui.set_text(gui.get_node("TokenText"),tokens)
		-- Set end game text to visible
		gui.set_visible(gui.get_node("endGameText"),true)
		-- Set end game text to You Win!
		gui.set_text(gui.get_node("endGameText"),"You Win!")
		-- Set the play again button to visible
		gui.set_visible(gui.get_node("playAgain"), true)
		gui.set_visible(gui.get_node("playAgainText"),true)

		-- Return to avoid unnecessary code execution
		return
	end

	-- If the player is out of flips (Only executes if the player has not won)
	if flipsLeft == 0 then
		-- Set gameEnd to true
		gameEnd = true
		-- Increase global match played
		MatchPlayed = MatchPlayed +1
		-- Set end game text to visible
		gui.set_visible(gui.get_node("endGameText"),true)
		-- Set end game text to You Lose!
		gui.set_text(gui.get_node("endGameText"),"You Lose!")
		-- Set the play again button to visible
		gui.set_visible(gui.get_node("playAgain"), true)
		gui.set_visible(gui.get_node("playAgainText"),true)

		-- Return to avoid unnecessary code execution
		return
	end

	-- Only executes if the user has not won and still has flips left
	
	-- Set evaluating to false so user can input again
	evaluating = false

end

-- Custom Function
-- Evaluates the 2 cards flipped over to determine if they match
local function pairEvaluate()
	
	-- If the chosen cards don't match
	if cardsPlace[currentPairFlipped[1]] ~= cardsPlace[currentPairFlipped[2]] then
		-- Set both cards to their back animations
		gui.play_flipbook(gui.get_node("card"..currentPairFlipped[1]), "fish-match-card-back")
		gui.play_flipbook(gui.get_node("card"..currentPairFlipped[2]), "fish-match-card-back")
		-- Set both positions of the flippedOver array to 0, indicating they are no longer flipped over
		flippedOver[currentPairFlipped[1]] = 0
		flippedOver[currentPairFlipped[2]] = 0
	end

	-- Sets flippedAmount back to 0
	flippedAmount = 0
	-- Resets the currentPairFlipped array
	currentPairFlipped = {0,0}

	-- If flipsLeft is less than 5, meaning 6 flips have been done so it's possible the player has won
	if flipsLeft < 5 then
		-- Calls winEvaluate to check if the player has won
		winEvaluate()
	-- If flipLeft is 5 or higher, meaning not flips have been made for the player to have won
	else
		-- Sets evaluating to false so the player can input 
		evaluating = false
	end

end

-- Custom Function
-- Called when a player clicks a card that isn't already flipped over as long as nothing is being evaluated
-- Handles changing the sprite, changing the number of flips the user has, and calling to evaluate the pair if 2 cards are flipped
local function flip(cardPosition)

	-- Subtract one from the flips left
	flipsLeft = flipsLeft - 1
	-- Set the on screen text to reflect the number of flips left
	gui.set_text(gui.get_node("FlipText"), "Flips: "..flipsLeft)
	-- Send a message to the loader to play the flip noise
	msg.post("Loader:/Loader","Sound", {sound = 2})

	-- Add one to the amount of cards flipped over
	flippedAmount = flippedAmount +1
	-- Add the flipped cards position to the currentPairFlipped array in the position it was flipped
	currentPairFlipped[flippedAmount] = cardPosition
	-- Set the card in the flippedOver array to 1 to represent being flipped (so the user can't click on it again until it's turned back over)
	flippedOver[cardPosition] = 1
	-- If flippedAmount is 1, so only one card has been flipped
	if flippedAmount == 1 then
		-- Set the card to the the correct face animation
		gui.play_flipbook(gui.get_node("card"..cardPosition), "Animation"..cardsPlace[cardPosition])
	-- If flipamount is 2, so 2 cards have been flipped
	elseif flippedAmount == 2 then
		-- Set evaluating to true to prevent the player from clicking more cards
		evaluating = true
		-- Set the card to the the correct face animation and call animation end to execute the validation after it's done
		gui.play_flipbook(gui.get_node("card"..cardPosition), "Animation"..cardsPlace[cardPosition], pairEvaluate)
	end

end

-- Custom function
-- This function sets up which cards are in what positions at the beginning of the game
local function cardSet()

	-- Iterates for each card in the game
	for i = 1, 6, 1 do

		-- calls a random number between 1 and 6
		local cardSelect = math.random(1,6)

		-- Checks if the position chosen has already been chosen, so is set to 0
		while cards[cardSelect] == 0 do
			-- Calls a new random number until they hit a position that hasn't been called yet
			cardSelect = math.random(1,6)
		end

		-- Sets the spot in card place to the selected card
		cardsPlace[i] = cards[cardSelect]
		-- Sets that spot in cards to 0 so the same card can't be chosen again. This ensures only 2 of each card is in 
		cards[cardSelect] = 0
		
	end

end

-- Custom Function
-- Resets all the variables and nodes so the game can be played from the beginning
local function Reset() 
	-- Reset the gameEnd variable
	gameEnd = false
	-- Resets the arrays and variables to their initial values
	cards = {1,1,2,2,3,3}
	cardsPlace = {0,0,0,0,0,0}
	flipsLeft = 10
	gui.set_text(gui.get_node("FlipText"), "Flips: "..flipsLeft)
	flippedAmount = 0
	currentPairFlipped = {0,0}
	flippedOver = {0,0,0,0,0,0}
	evaluating = false
	-- Sets all the game end nodes to not visible
	gui.set_visible(gui.get_node("endGameText"), false)
	gui.set_visible(gui.get_node("playAgain"), false)
	gui.set_visible(gui.get_node("playAgainText"),false)
	-- Sets all the cards to the back animation
	for i=1,6,1 do
		gui.play_flipbook(gui.get_node("card"..i), "fish-match-card-back")
	end
	-- Calls cardSet to get a new card distribution
	cardSet()
end

-- Execute when the script is first loaded
function init(self)
	-- Acquires input focus
	msg.post(".","acquire_input_focus")
	-- Sets the on screen token text
	gui.set_text(gui.get_node("TokenText"),tokens)
	-- Seeds the random 
	math.randomseed(socket.gettime() * 100000)
	-- Calls cardSet to set up the game
	cardSet()
end

-- Executes when when the script receives input
function on_input(self, action_id, action)

	-- If the player left clicks
	if action_id == hash("LeftClick") and action.pressed then

		-- Get the return arrow node
		local goBack = gui.get_node("Exit")

		-- If the user clicks the arrow to go back
		if gui.pick_node(goBack, action.x, action.y) then
			-- Calls the loader to load the mini game select
			msg.post("Loader:/Loader", "load MiniGameSelect")
		end

		-- If the player has not won or lost
		if not evaluating then

			-- Get the 6 card nodes
			local cardNodes = {gui.get_node("card1"),gui.get_node("card2"),gui.get_node("card3"),gui.get_node("card4"),gui.get_node("card5"),gui.get_node("card6")}

			-- Checks if the player clicked any of the card
			-- Iterate through the card nodes array
			for i=1,#cardNodes do
				-- Check if this node was the one clicked on 
				if gui.pick_node(cardNodes[i], action.x, action.y) then
					-- If the node isn't already flipped over
					if flippedOver[i] ~= 1 then
						-- Call the flip function with the node number
						flip(i)
					end
				end
			end

		-- If the game has ended (the player has lost or won)
		elseif gameEnd then

			-- Get the playAgain button
			local playAgain = gui.get_node("playAgain")
			
			-- If the user clicks the play again button
			if gui.pick_node(playAgain, action.x, action.y) then
				-- Call reset to reset the game
				Reset()
			end

		end
	
	end
	
end

-- Executes when the script receives a message
function on_message(self, message_id, message, sender)

	-- If message id is Update (sent from the loader)
	if message_id == hash("Update") then

		-- Sets the text for the Tokens text
		gui.set_text(gui.get_node("TokenText"),tokens)
		-- Calls reset to set the game back to the beginning
		Reset()
		
	end

end

-- Unused Functions

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
