
local clickAllowed = false

local function loadCrane(self)

	msg.post("Loader:/Loader", "load Crane")
	
end

local function screenFade(self)
	local to_color = gui.get_color(self.black)
	to_color.w = 1
	gui.animate(self.black, gui.PROP_COLOR, to_color, gui.EASING_IN, 1, 0, loadCrane)
end

local function textFlash(self)
	local to_color = gui.get_color(self.clickText)
	to_color.w = 1
	gui.animate(self.clickText, gui.PROP_COLOR, to_color, gui.EASING_IN, 1.8, 0, nil, gui.PLAYBACK_LOOP_PINGPONG)
	clickAllowed = true
end

local function show_title(self)
	local to_color = gui.get_color(self.logo)
	to_color.w = 1
	gui.animate(self.logo, gui.PROP_COLOR, to_color, gui.EASING_IN, 1, 0, textFlash)
end

local function show_background(self)
	local d = .75
	local to_color = gui.get_color(self.background)
	to_color.w = 1
	gui.animate(self.background, gui.PROP_COLOR, to_color, gui.EASING_IN, 1, d, show_title)
end

function init(self)
	msg.post(".", "acquire_input_focus")

	self.background = gui.get_node("background")
	self.logo = gui.get_node("Sign")
	self.clickText = gui.get_node("Text")
	self.black = gui.get_node("Black")

	show_background(self)
end

function on_input(self, action_id, action)

	if clickAllowed then
		if action_id == hash("LeftClick") and action.pressed then
			screenFade(self)
		end
	end
	
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
