
-- Boolean tracks whether the game has started
local gameStart = false

-- Keeps track of the ID of the spawned course object for moving
local selfID = 0

-- Executes once per frame
function update(self, dt)

	-- Checks if the gameStart variable is true. 
	if gameStart then

		-- Gets the position of the course as a vector3
		local pos = go.get_position(selfID)
		-- Subtract 3 from the x position, so it moves to the left
		pos.x = pos.x - 3
		-- Set the course position to the new position
		go.set_position(pos,selfID)

	end

end

-- Executes when the script receives a message
function on_message(self, message_id, message, sender)

	-- If the message ID is died
	if message_id == hash("died") then
		-- Set died to true
		gameStart = false
	-- If the message ID is gameStart
	elseif message_id == hash("gameStart") then
		-- Set gameStart to true
		gameStart = true
	end

end

-- Executes when the script first loads
function init(self)
	
	-- Saves it's Object ID
	selfID = go.get_id()
	-- Set the variables to false
	gameStart = false
	
end
