
-- Load Global Variables

-- Gets path to file (platform specific)
path = sys.get_save_file("FishingWithCrane", "testing")

-- Loads the data from that
data = sys.load(path)

-- Custom funciton
-- Called when a player does not have a save file
-- Sets up a Lua table with all global variables set to initial values
-- Saves the Lua table to the file
-- Loads the table into the data variable
function newData()

	-- Lua Table of global variables
	progressData = {
		-- Variable to keep track of whether the user has data
		firstLoad = false,
		-- Users token number
		tokens = 3,
		-- Array keeping track of what freshwater fish the player has seen
		FreshwaterFishSeen = {0,0,0,0,0,0,0,0},
		-- Array keeping track of how many of each freshwater fish the player has
		FreshwaterFish = {0,0,0,0,0,0,0,0},
		-- Array keeping track of what saltwater fish the player has seen
		SaltwaterFishSeen = {0,0,0,0,0,0,0,0},
		-- Array keeping track of how many of each saltwater fish the player has
		SaltwaterFish = {0,0,0,0,0,0,0,0},
		-- Array keeping track of what decor the player has seen
		TankDecorSeen = {0,0,0,0,0,0,0,0},
		-- Array keeping track of how many of each decor the player has
		TankDecor = {0,0,0,0,0,0,0,0},
		-- Integer to keep track of total fish pulled from the crane
		TotalFishPulled = 0,
		-- Array to keep track of the fiftieth fish pulled. Position 1 = set, Position 2 = number
		FiftiethFish = {0,0},
		-- Fish Tac Toe variables, keeps track of the number of times the player wins, losses, and stalemates
		FishTacToeWins = 0,
		FishTacToeLosses = 0,
		FishTacToeStalemates = 0,
		-- Number of times Match is played
		MatchPlayed = 0,
		-- Array keeping track of which flappy fish courses have been completed
		coursesComplete = {0,0,0},
		-- Integer keeping track of how many times a fish has been clicked
		petFish = 0
	}

	-- Saves the array to the file path
	sys.save(path,progressData)
	-- Loads the fresh array to the data variable
	data = sys.load(path)

end

-- Checks if the data variable is empty after being loaded
if next(data) == nil then

	-- Calls newData() to load the global variables to the file
	newData()

end

-- Custom Function
-- Used when the coin sound finishes playing, triggered from clicking the crane
-- Plays the crane operation sound
local function soundEnd(self)

	-- Lets the MainCraneScreen know that the coin sound is done playing so it can play the crane animation
	msg.post("main:/CraneScreenGUI#MainCraneScreen","Coin Done")
	-- Plays the sound of the crane moving alongside the crane animation
	sound.play("go#CraneOperation")
	
end

-- Custom Function
-- Handles which sounds should be played when a sound is requested
local function playNoise(soundNumber)

	-- Triggered when a player clicks on the fish in the detailed view
	if soundNumber == 1 then
		sound.play("go#FishNoise")
		
	-- Triggered when players flip a card in the match game
	elseif soundNumber == 2 then
		sound.play("go#CardFlip")
		
	-- Triggered when player clicks crane on the main page, plays a noise of a coin going into a slot
	elseif soundNumber == 3 then
		-- When the sounds end it triggers other sounds and animatoins
		sound.play("go#CoinIn", nil, soundEnd)
		
	-- Triggered when the fish appears after the Crane animation plays
	elseif soundNumber == 4 then
		sound.play("go#WinFish")
		
	-- Triggered when player or bot place a symbol in tic tac toe
	elseif soundNumber == 5 then
		sound.play("go#TicTacToePlace")
		
	end
	
end

-- Custom Function
-- Checks the fragment against all possible options to disable the correct scene
-- Sends a message to the collection proxy to disable it
local function disableSender(fragment)

	-- Achievements
	if fragment == hash("Achievements") then
		msg.post("#Achievements", "disable")
		
	-- Collection
	elseif fragment == hash("Collection") then
		msg.post("#Collection", "disable")
		
	-- Mini Game Select 
	elseif fragment == hash("MiniGameSelect") then
		msg.post("#MiniGameSelect", "disable")

	-- Crane
	elseif fragment == hash("MainCraneScreen") then
		msg.post("#Crane", "disable")
		
	-- Item Collection 
	elseif fragment == hash("ItemCollection") then
		msg.post("#ItemCollection", "disable")
		
	-- Fish Tank
	elseif fragment == hash("FishTank") then
		msg.post("#FishTank","disable")

	-- Detailed Fish
	elseif fragment == hash("DetailedFish") then
		msg.post("#DetailedFish", "disable")
	
	-- TicTacToe
	elseif fragment == hash("FishTacToe") then
		msg.post("#FishTacToe", "disable")
		
	-- Match
	elseif fragment == hash("Match") then
		msg.post("#FishMatch","disable")
	
	-- FlappyFish
	elseif fragment == hash("FlappyFish") then
		msg.post("#FlappyFish","disable")
		
	-- Title Screen
	elseif fragment == hash("TitleScreen") then
		msg.post("#TitleScreen","disable")

	-- Credits
	elseif fragment == hash("Credits") then
		msg.post("#Credits","disable")
		
	end
	
end

-- Runs the first time that the script is loaded
function init(self)
	
	-- Acquires input focus 
	msg.post(".","acquire_input_focus")

	-- Loads all of the collections when the game loads
	msg.post("#TitleScreen","load")
	msg.post("#Crane","load")
	msg.post("#Collection","load")
	msg.post("#ItemCollection", "load")
	msg.post("#DetailedFish","load")
	msg.post("#Achievements","load")
	msg.post("#MiniGameSelect","load")
	msg.post("#FishTacToe", "load")
	msg.post("#FishMatch","load")
	msg.post("#FlappyFish", "load")
	msg.post("#FishTank", "load")
	msg.post("#Credits", "load")

	-- Begins playing the background song
	sound.play("go#BackgroundSong")
	
end

-- Executes when the script receives a message
function on_message(self, message_id, message, sender)

	-- If the loader receives a message with the hash sound
	if message_id == hash("Sound") then
		-- Calls play noise and passes the number of the sound that was called
		playNoise(message.sound)
	end

	-- Message sent back when the Proxy collections finishes loading
	-- Only executes at the beginning when all of the collections load
	if message_id == hash("proxy_loaded") then

		-- Tells the sender (proxy which was loaded) to initialize (execute init() code)
		msg.post(sender, "init")

		-- If the sender (the proxy that loaded) is the Crane page, it is sent a message to enable
		if sender.fragment == hash("TitleScreen") then

			-- Sends a message to the loaded proxy enabling it, making it visible
			msg.post(sender, "enable")
			-- Sends a message to the title screen with whether firstLoad is true or false
			msg.post("TitleScreen:/TitleScreen#TitleScreen", "info", {delete = data["firstLoad"]})
							
		end

	-- Message received to load the ManeCraneScreen, where you can pick sets and pull on the crane
	elseif message_id == hash("load Crane") then
		-- Enable the crane proxy
		msg.post("#Crane", "enable")
		-- Send a message to the crane collection to update GUI elements tied to global variables
		msg.post("main:/CraneScreenGUI#MainCraneScreen", "Update")

		-- Passes the sender fragment to disable to sender
		disableSender(sender.fragment)

	-- If the message is to load the collection selection page 
	elseif message_id == hash("load Collection") then
		-- Enable the collection proxy
		msg.post("#Collection", "enable")
		-- Sends a message to the collection seen to let it know to reset
		msg.post("Collection:/CollectionGUI#Collection","Opening")

		-- Passes the sender fragment to disable to sender
		disableSender(sender.fragment)

	-- If the message is to load the item collection page
	elseif message_id == hash("load itemCollection") then
		-- Enable the collection proxy
		msg.post("#ItemCollection", "enable")
		-- Sends a message to the item collection to update, passing the selected set to display
		msg.post("ItemCollection:/ItemCollection#ItemCollection","Update",{set = message.set})

		-- Passes the sender fragment to disable to sender
		disableSender(sender.fragment)
		
	-- If the message was to load the Achievement page
	elseif message_id == hash("load Achievement") then
		-- Enable the achievement collction so it can be seen
		msg.post("#Achievements", "enable")
		-- Send a message to the achievements page to update and display the achievements
		msg.post("Achievements:/Achievements#Achievements", "Display")

		-- Passes the sender fragment to disable to sender
		disableSender(sender.fragment)

	-- If the message was to load the mini game select page
	elseif message_id == hash("load MiniGameSelect") then
		-- enable the mini game select collection
		msg.post("#MiniGameSelect", "enable")

		-- Passes the sender fragment to disable to sender
		disableSender(sender.fragment)

	-- If the message was to load the Tic Tac Toe minigame
	elseif message_id == hash("load FishTacToe") then
		-- enable the mini game select collection
		msg.post("#FishTacToe", "enable")
		-- Send a message to the tic tac toe collection to update GUI elements tied to global variables
		msg.post("FishTacToe:/FishTacToe#FishTacToe", "Update")

		-- Passes the sender fragment to disable to sender
		disableSender(sender.fragment)

	-- If the message was to load the Match minigame
	elseif message_id == hash("load FishMatch") then
		-- enable the Match collection
		msg.post("#FishMatch","enable")
		-- Send a message to the Match collection to update GUI elements tied to global variables
		msg.post("Match:/Match#Match", "Update")

		-- Passes the sender fragment to disable to sender
		disableSender(sender.fragment)

	-- If the message was to load the Flappy Fish minigame
	elseif message_id == hash("load FlappingFish") then
		-- enable the Flappy Fish collection
		msg.post("#FlappyFish","enable")
		-- Send a message to the Flappy Fish collection to update GUI elements tied to global variables
		msg.post("FlappyFish:/FlappyFishGUI#FlappyFish", "Update")

		-- Passes the sender fragment to disable to sender
		disableSender(sender.fragment)

	-- If the message was to load the Fish Tank
	elseif message_id == hash("load FishTank") then
		-- enable the Fish Tank page
		msg.post("#FishTank","enable")
		-- Send a message to the fish tank to update it's opening animation
		msg.post("FishTank:/FishTankGUI#FishTank","Opening")

		-- Passes the sender fragment to disable to sender
		disableSender(sender.fragment)

	-- If the message was to load the Detailed Fish inventory page
	elseif message_id == hash("load DetailedFish") then
		-- enable the detailed inventory page
		msg.post("#DetailedFish", "enable")
		-- Send a message to the detailed inventory page, providing which set is being called and which fish
		msg.post("DetailedFish:/DetailedFish#DetailedFish","setUp", {set = message.set, fish = message.fish})

		-- Passes the sender fragment to disable to sender
		disableSender(sender.fragment)

	elseif message_id == hash("load Credits") then
		-- enable the credits page
		msg.post("#Credits", "enable")

		-- Passes the sender fragment to disable to sender
		disableSender(sender.fragment)
	end
	
end